- name: Download upstream files
  run: |
    BASE_URL="https://raw.githubusercontent.com/v2rayA/dist-v2ray-rules-dat/master"

    FILES="
    apple-cn.txt
    china-list.txt
    direct-list.txt
    direct-tld-list.txt
    geoip.dat
    geoip.dat.sha256sum
    geosite.dat
    geosite.dat.sha256sum
    gfw.txt
    google-cn.txt
    greatfire.txt
    proxy-list.txt
    proxy-tld-list.txt
    reject-list.txt
    rules.zip
    rules.zip.sha256sum
    win-extra.txt
    win-spy.txt
    win-update.txt
    "

    for file in $FILES; do
      echo "Downloading $file"

      wget -q -O "$file" "$BASE_URL/$file" || echo "Skip $file"
    done
